#!/bin/bash
export JOBS="1 2 3 4 5"                           # 3D multipliers: NTASKS=i^3, res=BASE*i
export RUN_INDICES="1 2 3"                        # repetitions for averaging
export WALLTIME="02:00:00"

export SCALING_TYPE=1               # 1=weak, 2=strong
export SCALING_BASE=8
export PBSTASK_MULT=1               # multiplier for requested PBSTASKS so you can increase memory request (e.g. use 384 GB, but you only need < 48 procs)

export UW_DIM=3                     # 2 or 3

export UW_SOL_TOLERANCE=1e-50       # tolerance to use

# Space-separated list of model filenames (w/o extension) to run in sequence.
# The launcher will submit one job per model per JOBS x RUN_INDICES combination.
export UW_MODELS="poisson-scaling"
export UW_MODEL="poisson-scaling"   # fallback / single-model override (set by launcher per iteration)

export UW_NAME="uw3_Jul2026_baremetal_BASE8"  # uw version name label

# Base output path — replaces the hardcoded /scratch/el06/jg0883/ in Python scripts.
export OUTPUT_BASE="/scratch/el06/jg0883"

# Shared mesh cache — pre-generated by generate_meshes.py, reused by all scaling scripts.
export MESH_CACHE="${OUTPUT_BASE}/mesh_cache"

export PICKLENAME=None              # "None" to disable conv testing
###

export ACCOUNT="el06"
export QUEUE="normal"               # normal or express

# Set to 1 to run jobs inside the Singularity container (gadi_container_go.sh)
# instead of the baremetal environment (gadi_baremetal_go.sh).
# Requires: pip install --target=/scratch/el06/jg0883/uw3-extra-pkgs assess  (once)
export USE_CONTAINER=0

# Test style - UW_MAX_ITS:
#   For vep-scaling / advdiff-scaling: number of timesteps (>= 2 recommended so first_solve
#   and steady_solves stages are distinct).
#   For stokes-scaling / poisson-scaling: max KSP/SNES iterations per solve.
export UW_MAX_ITS=10

# advdiff-scaling / vep-scaling: number of timesteps in the steady_solves stage.
# Independent of UW_MAX_ITS, which is the KSP iteration budget per solve — these were
# one knob until 2026-08-07, so changing the iteration budget silently changed how much
# physics was simulated.
export UW_NSTEPS=10

# stokes-scaling: overrides the fieldsplit inner tolerances, which UW3 otherwise derives
# from UW_SOL_TOLERANCE as tol*0.1 (pressure) and tol*0.033 (velocity). At tol=1e-8 those
# are 1e-9 / 3.3e-10 — tight enough that inner solves take many iterations, each costing a
# global MPI_Allreduce. Set >0 to loosen (1e-3 is conventional for a flexible outer
# method); 0 keeps the UW3-derived values.
export UW_INNER_RTOL=0

# MPI rank placement. Empty = OpenMPI's default dense packing (48 ranks/node), which
# makes ranks-per-node vary across an i^3 weak-scaling sweep (1, 8, 27, 48, 48) and so
# confounds efficiency with memory-bandwidth-per-rank. "--map-by node" distributes
# round-robin instead; needs PBSTASK_MULT>1 to supply the extra nodes.
export UW_MPI_MAP=""

# poisson-scaling: initial state for u. "zero" reproduces the original campaign, where the
# fixed-work protocol aborts SNES before it updates the solution, so u stays at zero and the
# k = 1 + u^2 diffusivity is indistinguishable from k = 1 — a plain Laplacian. "analytic"
# starts u at the MMS solution so k genuinely varies in space.
export UW_INIT="zero"

# NOTE: every variable here must ALSO be listed in EXPORTVARS in
# scaling_test_job_launcher.sh, or it will not reach the job.

# VEP integrator: 'etd' (ETD-1, recommended) or 'bdf' (BDF-1, legacy default).
export UW_VEP_INTEGRATOR="etd"

# Memory diagnostics: set to 1 to enable memprobe RSS tracking in vep/advdiff scripts.
export UW_MEMPROBE=0

# NavierStokes Reynolds number (ns-scaling.py).
export UW_NS_RE=100

# unused / legacy
export UW_PENALTY=-1.               # set to negative value to disable penalty
export UW_ENABLE_IO="0"
###
